---

- name: Ensure that Apache is installed
  yum: name=httpd state=present
  when: ansible_os_family == "RedHat"



- name: Start Apache Services
  service: name=httpd enabled=yes state=started



- name: Deploy configuration File
  template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
    - Restart Apache



- name: Copy Site Files
  template: src=templates/index.j2 dest={{ doc_root }}/index.html
